package proj;


import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

import static proj.Connections.con;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author EmadMohamed
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
   static boolean miximum=true ;
    int x;
    int y;
    ResultSet rs;
    Statement st;
 
     List<String> userlist=new ArrayList<>();
      List<String> passlist=new ArrayList<>();
    public register()  {
        
     
        initComponents();
        this.setLocationRelativeTo(this);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("User-1.png")));
        
     //------------get user and password to array list for compare-----------------//
        String sql="SELECT * FROM users" ;

        try {
            con=Connections.getConnection();   
            st=con.createStatement();
            rs=st.executeQuery(sql);
           while(rs.next()){
           
               userlist.add(rs.getString("username")); 
                passlist.add(rs.getString("password"));      
               
           }
         
            
        } catch (SQLException ex) {
           ex.getMessage();
        }
        
      //------------------------------------------//  
      Font tr=null;
     try{
        tr=Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("calibrib.ttf"));
         tr=tr.deriveFont(Font.BOLD,24);        
          kButton4.setFont(tr);
          kButton6.setFont(tr);               
     } catch (Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
     
     //-------------------------------------//
      Font trr=null;
     try{
        trr=Font.createFont(Font.TRUETYPE_FONT,getClass().getResourceAsStream("calibrib.ttf"));
         trr=trr.deriveFont(Font.BOLD,18);
         
          jLabel1.setFont(tr);
          jLabel2.setFont(tr);
          jLabel4.setFont(tr);

        
                       
     } catch (Exception e){
         JOptionPane.showMessageDialog(null, e);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pnltitle = new javax.swing.JPanel();
        kButton3 = new keeptoo.KButton();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        lbltitle = new javax.swing.JLabel();
        kButton4 = new keeptoo.KButton();
        kButton6 = new keeptoo.KButton();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("الاسم الكامل");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setText("كلمة السر");

        pnltitle.setBackground(new java.awt.Color(39, 47, 48));
        pnltitle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnltitleMouseDragged(evt);
            }
        });
        pnltitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnltitleMousePressed(evt);
            }
        });

        kButton3.setBackground(new java.awt.Color(38, 128, 207));
        kButton3.setForeground(new java.awt.Color(38, 128, 207));
        kButton3.setkBackGroundColor(new java.awt.Color(38, 128, 207));
        kButton3.setkBorderRadius(45);
        kButton3.setkEndColor(new java.awt.Color(38, 128, 207));
        kButton3.setkForeGround(new java.awt.Color(38, 128, 207));
        kButton3.setkHoverColor(new java.awt.Color(38, 128, 207));
        kButton3.setkHoverEndColor(new java.awt.Color(38, 128, 207));
        kButton3.setkHoverForeGround(new java.awt.Color(38, 128, 207));
        kButton3.setkHoverStartColor(new java.awt.Color(38, 128, 207));
        kButton3.setkIndicatorColor(new java.awt.Color(38, 128, 207));
        kButton3.setkPressedColor(new java.awt.Color(38, 128, 207));
        kButton3.setkSelectedColor(new java.awt.Color(38, 128, 207));
        kButton3.setkStartColor(new java.awt.Color(38, 128, 207));
        kButton3.setOpaque(false);
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton1.setBackground(new java.awt.Color(190, 207, 38));
        kButton1.setForeground(new java.awt.Color(190, 207, 38));
        kButton1.setkBackGroundColor(new java.awt.Color(190, 207, 38));
        kButton1.setkBorderRadius(45);
        kButton1.setkEndColor(new java.awt.Color(190, 207, 38));
        kButton1.setkForeGround(new java.awt.Color(190, 207, 38));
        kButton1.setkHoverColor(new java.awt.Color(190, 207, 38));
        kButton1.setkHoverEndColor(new java.awt.Color(190, 207, 38));
        kButton1.setkHoverForeGround(new java.awt.Color(190, 207, 38));
        kButton1.setkHoverStartColor(new java.awt.Color(190, 207, 38));
        kButton1.setkIndicatorColor(new java.awt.Color(190, 207, 38));
        kButton1.setkPressedColor(new java.awt.Color(190, 207, 38));
        kButton1.setkSelectedColor(new java.awt.Color(190, 207, 38));
        kButton1.setkStartColor(new java.awt.Color(190, 207, 38));
        kButton1.setOpaque(false);
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setBackground(new java.awt.Color(255, 0, 0));
        kButton2.setForeground(new java.awt.Color(255, 0, 0));
        kButton2.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        kButton2.setkBorderRadius(45);
        kButton2.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton2.setkForeGround(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverColor(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton2.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton2.setkIndicatorColor(new java.awt.Color(255, 0, 0));
        kButton2.setkPressedColor(new java.awt.Color(255, 0, 0));
        kButton2.setkSelectedColor(new java.awt.Color(255, 0, 0));
        kButton2.setkStartColor(new java.awt.Color(255, 0, 0));
        kButton2.setOpaque(false);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        lbltitle.setFont(new java.awt.Font("DecoType Naskh Extensions", 1, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(255, 255, 255));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("أنشاء حساب");

        javax.swing.GroupLayout pnltitleLayout = new javax.swing.GroupLayout(pnltitle);
        pnltitle.setLayout(pnltitleLayout);
        pnltitleLayout.setHorizontalGroup(
            pnltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltitleLayout.createSequentialGroup()
                .addContainerGap(129, Short.MAX_VALUE)
                .addComponent(lbltitle, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnltitleLayout.setVerticalGroup(
            pnltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnltitleLayout.createSequentialGroup()
                .addGroup(pnltitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(kButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(kButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnltitleLayout.createSequentialGroup()
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(lbltitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        kButton4.setBorder(null);
        kButton4.setText("تسجيل");
        kButton4.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        kButton4.setkBackGroundColor(new java.awt.Color(38, 128, 207));
        kButton4.setkBorderRadius(15);
        kButton4.setkEndColor(new java.awt.Color(38, 128, 207));
        kButton4.setkHoverEndColor(new java.awt.Color(38, 128, 207));
        kButton4.setkHoverForeGround(new java.awt.Color(38, 128, 207));
        kButton4.setkHoverStartColor(new java.awt.Color(38, 128, 207));
        kButton4.setkSelectedColor(new java.awt.Color(38, 128, 207));
        kButton4.setkStartColor(new java.awt.Color(38, 128, 207));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton6.setText("الغاء");
        kButton6.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        kButton6.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        kButton6.setkBorderRadius(15);
        kButton6.setkEndColor(new java.awt.Color(255, 0, 0));
        kButton6.setkHoverEndColor(new java.awt.Color(255, 0, 0));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 0, 0));
        kButton6.setkHoverStartColor(new java.awt.Color(255, 0, 0));
        kButton6.setkSelectedColor(new java.awt.Color(255, 0, 0));
        kButton6.setkStartColor(new java.awt.Color(255, 0, 0));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jTextField8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel4.setText("اسم المستخدم");

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(36, 36, 36)
                                    .addComponent(jLabel1))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                        .addComponent(jPasswordField1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))))))
                    .addComponent(pnltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(pnltitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed

        if(miximum){
            register.this.setExtendedState(JFrame.MAXIMIZED_BOTH);
            GraphicsEnvironment ge=GraphicsEnvironment.getLocalGraphicsEnvironment();
            register.this.setMaximizedBounds(ge.getMaximumWindowBounds());
            miximum=false;
        }
        else{
            setExtendedState(JFrame.NORMAL);
            miximum=true;
        }

    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
       dispose();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void pnltitleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnltitleMouseDragged
        int xx=evt.getXOnScreen();
        int yy=evt.getYOnScreen();
        this.setLocation(xx-x, yy-y);
    }//GEN-LAST:event_pnltitleMouseDragged

    private void pnltitleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnltitleMousePressed
        x=evt.getX();
        y=evt.getY();
    }//GEN-LAST:event_pnltitleMousePressed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
 String sql="INSERT INTO users (name,username, password)VALUES (?,?,?)";
       con=Connections.getConnection();
       try{
        PreparedStatement pst=con.prepareStatement(sql); 
    ;
      
        pst.setString(1, jTextField7.getText());
        
        pst.setString(2, jTextField8.getText());
         
        pst.setString(3, jPasswordField1.getText());
    
        
        
         pst.executeUpdate();
         JOptionPane.showMessageDialog(null, "تم انشاء الحساب بنجاح");
     
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
       

    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed

          dispose();
        
        
        jTextField7.setText("");
        jTextField8.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_kButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new register().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton6;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JPanel pnltitle;
    // End of variables declaration//GEN-END:variables
}
